name: Build on Windows

on:
  push:
    branches: [ci-test]
  workflow_dispatch:

jobs:
  build-server:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install xmake
        shell: pwsh
        run: |
          winget install xmake --silent --accept-source-agreements
          xmake --version

      - name: Build server
        shell: pwsh
        run: xmake build server
