name: Build on Windows

on:
  push:
    branches: [ci-test]
  workflow_dispatch:

jobs:
  build-server:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - run: |
          choco install xmake -y
          $env:PATH += ";$env:ProgramData\chocolatey\bin"
          xmake --version
        shell: pwsh

      - run: |
          $env:PATH += ";$env:ProgramData\chocolatey\bin"
          xmake build server
        shell: pwsh
